### ISSUE TITLE
$last

### ISSUE THREAD

**Issue by giangi007** [erikszewczyk/DarkSky_Weather_API_PHP_MySQL#1]
Hello, I tried your php code, I'm able to connect to databse, but unfortunaly I received this allarm message: Notice: Undefined variable: last in C:\xampp\htdocs\progetti\Web-enabled_Thermostat-master\provawusql.php on line.
Could you check the code please?

Thanks

**Comment by erikszewczyk** [comment]
Sorry for not responding earlier, have notifications turned off on this repo

This would occur if there isn't a row in the table for your unique location id - you'll have to create a row in the table that equals to the location id you specify in the PHP else it cant match up records and confirm if you've got an up to date cache.  I'll add a note to the readme to help clarify that you need to perform this manual step.
